apiVersion: v1
kind: Namespace
metadata:
  name: sensit-stuff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: sensit-stuff
  labels:
    app: docs
spec:
  selector:
    matchLabels:
      app: docs
  replicas: 1   
  template:
    metadata:
      labels:
        app: docs
        privacyLevel: "sensit"
    spec:
      volumes:
        - name: docs-storage
          persistentVolumeClaim:
            claimName: docs-pvc
      containers:
        - image: zadam/trilium:latest
          name: trilium
          volumeMounts:
            - name: docs-storage
              mountPath: /home/node/trilium-data

