apiVersion: v1
kind: Namespace
metadata:
  name: sensit-stuff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitty
  namespace: sensit-stuff
  labels:
    app: bitty
spec:
  selector:
    matchLabels:
      app: bitty
  replicas: 1   
  template:
    metadata:
      labels:
        app: bitty
        privacyLevel: "sensit"
    spec:
      volumes:
        - name: bitty-storage
          persistentVolumeClaim:
            claimName: bitty-pvc
      containers:
      - image: vaultwarden/server:latest
        name: vwarden
        volumeMounts:
            - name: bitty-storage
              mountPath: /data

